// <auto-generated />
using System;
using Game.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Game.Backend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260311190617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Game.Backend.Entities.GameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "CreatedAtUtc");

                    b.HasIndex("LobbyId", "CreatedAtUtc");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Entities.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("Score");

                    b.HasIndex("Wins");

                    b.ToTable("leaderboards", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Entities.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HostPlayerId");

                    b.ToTable("lobbies", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Entities.LobbyMember", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LobbyId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("lobby_members", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Entities.GameEvent", b =>
                {
                    b.HasOne("Game.Backend.Entities.GameSession", "Game")
                        .WithMany("Events")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Game.Backend.Entities.Lobby", "Lobby")
                        .WithMany("Events")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Game.Backend.Entities.Player", "Player")
                        .WithMany("Events")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("Lobby");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Backend.Entities.GameSession", b =>
                {
                    b.HasOne("Game.Backend.Entities.Lobby", "Lobby")
                        .WithMany("Games")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("Game.Backend.Entities.LeaderboardEntry", b =>
                {
                    b.HasOne("Game.Backend.Entities.Player", "Player")
                        .WithOne("Leaderboard")
                        .HasForeignKey("Game.Backend.Entities.LeaderboardEntry", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Backend.Entities.Lobby", b =>
                {
                    b.HasOne("Game.Backend.Entities.Player", "HostPlayer")
                        .WithMany("HostedLobbies")
                        .HasForeignKey("HostPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HostPlayer");
                });

            modelBuilder.Entity("Game.Backend.Entities.LobbyMember", b =>
                {
                    b.HasOne("Game.Backend.Entities.Lobby", "Lobby")
                        .WithMany("Members")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Backend.Entities.Player", "Player")
                        .WithMany("LobbyMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Backend.Entities.GameSession", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Game.Backend.Entities.Lobby", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Games");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Game.Backend.Entities.Player", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("HostedLobbies");

                    b.Navigation("Leaderboard");

                    b.Navigation("LobbyMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
